### ISSUE TITLE
Need a way to receive public keys from clients to decode JWTs

### ISSUE THREAD

**Issue by asabine** [asabine/lighthouse#7]

**Comment by meitar** [comment]
The way I'm imagining this is that the Buoy plugin on the WordPress (client) side will automatically create a keypair, probably using the WP PGP Encrypted Emails plugin I wrote for exactly this purpose, when it is installed. Then, Buoy will check to see if the site on which it is installed has public registration configured and, if so, automatically opt-in to sending its telemetry to Lighthouse.

What I'd like to do is define a kind of a signup API for a Buoy in Lighthouse, so that I can make an HTTP request to you, and indicate in this request that this is a Buoy's first-time install/opt-in to telemetry. This should be an HTTPS POST so that I can send you the public key from the keypair that belongs to the site.

That way, the user experience for a Buoy admin is simply to install the plugin. They shouldn't have to worry about telemetry unless they want to, for example, rekey, but that should be a manual procedure anyway and we can worry about exposing a UI for this much later.

**Comment by asabine** [comment]
yeah, i'm thinking we can send the keys as a JWK ([RFC7517](https://www.rfc-editor.org/rfc/rfc7517.txt)) for consistency. should we have people sign up with user accounts on lighthouse itself? auto-register clients' keys on first use? or just set up a public key transaction on each request?

also, if we wanna do the key transaction in a separate request/response we'd have to find a way to pass a given public key to the view that updates the information; or a way to uniquely identify which public key to use to decode & verify the data. since the server's public key will already be known by clients we could just include the JWT containing the actual telemetry info as a private claim in a JWK like:
```
{
    "kty":"RSA",
    "n": "0vx7agoebGcQSuuPiLJXZptN9nndrQmbXEps2aiAFbWhM78LhWx4cbbfAAtVT86zwu1RK7aPFFxuhDR1L6tSoc_BJECPebWKRXjBZCiFV4n3oknjhMstn64tZ_2W-5JsGY4Hc5n9yBXArwl93lqt7_RN5w6Cf0h4QyQ5v-65YGjQR0_FDW2QvzqY368QQMicAtaSqzs8KJZgnYb9c7d0zgdAZHzu6qMQvRL5hajrn1n91CbOpbISD08qNLyrdkt-bFTWhAI4vMQFh6WeZu0fM4lFd2NcRwr3XPksINHaQ-G_xBniIqbw0Ls1jF44-csFCur-kEgU8awapJzKnqDKgw",
    "e":"65537",
    "alg":"RS256",
    "kid":"some identifier",
    "tkn": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InR5cGUiOiJjbGllbnQiLCJhdHRyaWJ1dGVzIjp7Im5hbWUiOiJGaXJzdCBOZXcgQnVveSBUZXN0IENsaWVudCIsInVybCI6Imh0dHBzOi8vdGVzdGNsaWVudC5mYWtlLzEiLCJjb3VudHJ5IjoiVVMiLCJwcm92aW5jZSI6Ik5ZIiwiY2l0eSI6Ik5ldyBZb3JrIENpdHkiLCJyZWdpc3RyYXRpb25zIjoib3BlbiIsImlzX2h0dHBzIjowLCJwb3B1bGF0aW9uIjoxM319fQ.T4bh24PLncxaEfs5A6G-478BNPMr75Qj4Zr4TjcxFo0vKqxMO0qieIWEppJCAnhVEcrGeXWbztnyH-ntwIe12B4XkkZ4um0cwOHERjnPjKc0-DdUHmgxStC0zhsOjJsXVwnRCSJmuTq-XuJN8UPhk1SR8BVK9zguQ3Cmgtlw0rc"
}
```
where `"tkn"` is the signed token containing the telemetry payload verified with the public key `"n"`

i was considering encrypting the payload contained within the JWT as well, so that way it could only be opened by lighthouse's private key but i'm still figuring it out since this is my first time working with crypto stuff

**Comment by asabine** [comment]
ok so i implemented the above in https://github.com/asabine/lighthouse/commit/71b4b31876326db8bb28a06e8002ef3c9a25d17e but i'm unsure whether or not there's a better way.

**Comment by meitar** [comment]
> if we wanna do the key transaction in a separate request/response we'd have to find a way to pass a given public key to the view that updates the information

You know more about JWT than I do but I imagine it's pretty standard, so take what I'm about to say next with that grain of salt.

The reason I think a separate request/response is useful is because we want a way to be explicit about a given Buoy *beginning* to send telemetry. I.e., "Hi, I am a new Buoy!" is different than, "Here is some updated information about me." This also means Lighthouse can be smarter about key management, basically refusing to accept a public key it hasn't seen before in a "Here is some updated information about me" request. This is effectively a Trust On First use (TOFU) system where Lighthouse will trust a new key it hasn't seen before so long as it's recording a never-before-seen Buoy and then require this same key for all updates.

Regarding encrypting the payload, I still don't really see why this is required, given that we're already going to require TLS so that clients can be assured they're talking to the only Lighthouse server they know about (we can use [HPKP](https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning) to ensure clients validate and reject any certificates we don't issue ourselves), but if you want to take this as an excuse to play with encryption, go for it. :)

Also, regardless, it sounds like you're getting pretty close to needing something concrete from me on the Buoy client side. Maybe we should schedule a time to videochat and make sure we get on the same page soon.
